---
- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - entr
      - libgmp-dev
      - libz3-dev
      - ripgrep  # For Telescope
      # For pyright
      - nodejs
      - npm
    update_cache: true
  become: true
