# ansible-playbook -K playbook.yml -i hosts
---
- name: Setup workstation
  hosts: local
  roles:
  # set caps lock to escape: https://askubuntu.com/a/365701
  #     + Dropbox
  #     + set up obsidian with Dropbox
    - prelude
    - fonts
    - dotnet
    - python
    - github-cli
    - haskell
    # - dropbox
    - neovim
    # - obsidian
    - starship
    - vscode