---
- name: Install VSCode
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  become: true
    
- name: Install VSCode
  become: true
  block:
    - name: Add VSCode APT repository
      ansible.builtin.deb822_repository:
        name: vscode
        types: [deb]
        uris: https://packages.microsoft.com/repos/code
        signed_by: https://packages.microsoft.com/keys/microsoft.asc
        suites: [stable]
        components: [main]
        state: present
        enabled: yes

    - name: Install VSCode
      ansible.builtin.apt:
        name: code
        update_cache: true

- name: Install Visual Studio Code Extensions
  shell: code --install-extension {{ item }}
  loop: 
    - asvetliakov.vscode-neovim
    - charliermarsh.ruff
    - haskell.haskell
    - ms-python.python

# TODO: settings.json
# {
#   "editor.fontFamily": "'Iosevka Nerd Font'",
#   "editor.fontLigatures": true,
#   "keyboard.dispatch": "keyCode",
# }
