---
- name: Install starship.rs
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes
  become: true

- name: Add to .bashrc
  ansible.builtin.lineinfile:
    line: eval "$(starship init bash)"
    path: ~/.bashrc
