---
- name: Install Nerd Fonts
  ansible.builtin.include_tasks: nerd-font.yml
  loop:
    - Iosevka

- name: Install Inter
  ansible.builtin.include_tasks: inter.yml
- name: Re-generate font cache files
  ansible.builtin.command: fc-cache -fv
  become: true
